### ISSUE TITLE
deepEqual() doesn't fail

### ISSUE THREAD

**Issue by jamesshore** [jokeyrhyme/assertive-chai.js#4]
`assert.deepEqual(1, 3);` should fail, but it doesn't do anything. v1.0.0.

**Comment by jokeyrhyme** [comment]
I just added some tests but can't reproduce this issue. `assert.deepEqual(1, 3);` throws, and `assert.notDeepEqual(1, 3);` does not throw.

**Comment by jamesshore** [comment]
I'll try to reproduce it with a simple example.

**Comment by jamesshore** [comment]
Okay, I just reproduced it. Steps to reproduce:
1. Start in an empty directory.
2. `npm install assertive-chai@1.0.0`
3. Save 'runme.js' containing this code:
   
   ``` javascript
   var assert = require("assertive-chai").assert;
   
   console.log("The next line should throw an exception...");
   assert.deepEqual(1, 3);
   console.log("...but it didn't.");
   
   console.log("A regular assert fails just fine:");
   assert.equal(1, 3);
   ```
4. `node runme.js`
5. Observe output:
   
   ```
   jamesshore:assertive-chai-bug jshore$ node runme.js 
   The next line should throw an exception...
   ...but it didn't.
   A regular assert fails just fine:
   
   assert.js:92
    throw new assert.AssertionError({
          ^
   AssertionError: 1 == 3
      at Object.<anonymous> (/Users/jshore/Documents/Projects/spikes/assertive-chai-bug/runme.js:13:8)
      at Module._compile (module.js:456:26)
      at Object.Module._extensions..js (module.js:474:10)
      at Module.load (module.js:356:32)
      at Function.Module._load (module.js:312:12)
      at Function.Module.runMain (module.js:497:10)
      at startup (node.js:119:16)
      at node.js:906:3
   jamesshore:assertive-chai-bug jshore$ 
   ```

**Comment by jamesshore** [comment]
node v0.10.32
npm v1.4.28

**Comment by jokeyrhyme** [comment]
Okay, I can see what's happening here. My function to confirm that errors are thrown by an assertion is broken. I'm fixing it now. :)

**Comment by jamesshore** [comment]
Fix confirmed, thank you.
